Repository googleapis/nodejs-datastore, pull requests merged in 2019-05, with the labels that each got.

#387 chore: remove Node.js v6 CI
  .kokoro/continuous/node6/common.cfg
  .kokoro/continuous/node6/test.cfg
  .kokoro/presubmit/node6/common.cfg
  .kokoro/presubmit/node6/test.cfg
Labels: cla: yes

#388 build!: upgrade engines field to >=8.10.0
  package.json
Labels: cla: yes

#389 chore: do not run CI on grpc-js
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
Labels: cla: yes

#395 build: patch Windows container, fixing Node 10
  .kokoro/test.bat
  package.json
Labels: automerge, cla: yes

#396 build: allow Node 10 to push to codecov
  .kokoro/continuous/node10/test.cfg
  .kokoro/continuous/node8/test.cfg
Labels: cla: yes

#397 build: allow Node 10 on presubmit to push to codecov
  .kokoro/presubmit/node10/test.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#394 build: only pipe to codecov if tests run on Node 10
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes, status: blocked

#399 fix: DEADLINE_EXCEEDED is no longer retried
  src/v1/datastore_client_config.json
  synth.metadata
Labels: cla: yes

#358 fix: correct Long types import
  package.json
  proto/datastore.d.ts
Labels: :rotating_light:, automerge, cla: yes

#403 fix: DEADLINE_EXCEEDED retry code is idempotent
  src/v1/datastore_client_config.json
  synth.metadata
Labels: cla: yes

#405 refactor: use repo-metadata to generate readme
  .clang-format
  .cloud-repo-tools.json
  .gitignore
  .repo-metadata.json
  README.md
  package.json
  samples/README.md
  samples/package.json
  synth.metadata
Labels: cla: yes

#407 chore: release 4.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#409 build: updated kokoro config for coverage and release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/release-candidate-issue.sh
  .kokoro/release-requested.sh
  .kokoro/release/publish.cfg
  .kokoro/release/release-candidate-issue.cfg
  .kokoro/release/release-requested.cfg
  .kokoro/test.sh
  synth.metadata
Labels: automerge, cla: yes

#410 refactor: drop dependency on lodash.merge and update links
  package.json
  samples/addTask.js
  src/v1/datastore_client.js
  synth.metadata
Labels: cla: yes

#412 chore: use published jsdoc-baseline package
  package.json
Labels: automerge, cla: yes, kokoro: force-run

#413 build: add configuration for automated doc deployment
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
Labels: cla: yes

#411 docs: add `Add Task` sample to index in README
  README.md
  samples/README.md
  synth.metadata
Labels: cla: yes

#418 build: ignore proto files in test coverage
  .nycrc
Labels: cla: yes

#419 fix: shell jobs were outputting too much information
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
Labels: cla: yes
