Repository googleapis/nodejs-datastore, pull requests merged in 2019-02, with the labels that each got.

#319 docs: add lint/fix example to contributing guide
  .github/CONTRIBUTING.md
Labels: cla: yes

#321 chore: move CONTRIBUTING.md to root
  CONTRIBUTING.md
Labels: cla: yes

#322 docs: update contributing path in README
  README.md
Labels: cla: yes

#305 refactor(types): enable noImplicitAny for transaction.ts & request.ts
  package.json
  proto/datastore.d.ts
  proto/entity.d.ts
  src/entity.ts
  src/index.ts
  src/request.ts
  src/transaction.ts
  system-test/datastore.ts
  test/transaction.ts
Labels: :rotating_light:, cla: yes

#323 build: test using @grpc/grpc-js in CI
  .kokoro/continuous/node8/system-test-grpcjs.cfg
  .kokoro/presubmit/node8/system-test-grpcjs.cfg
Labels: cla: yes

#324 refactor: asyncify the system test
  package.json
  src/index.ts
  src/query.ts
  src/request.ts
  src/transaction.ts
  system-test/datastore.ts
Labels: cla: yes

#325 refactor: clean up types for tests
  src/index.ts
  src/query.ts
  src/request.ts
  src/transaction.ts
  system-test/datastore.ts
  test/entity.ts
  test/index.ts
  test/query.ts
  test/request.ts
  test/transaction.ts
Labels: cla: yes

#328 build: create docs test npm scripts
  .kokoro/docs.sh
  package.json
Labels: cla: yes

#327 Release @google-cloud/datastore v3.1.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#331 fix: throw on invalid credentials
  src/v1/datastore_client.js
  synth.metadata
Labels: cla: yes

#334 docs: update links in contrib guide
  CONTRIBUTING.md
Labels: cla: yes

#332 build: use linkinator for docs test
  package.json
Labels: cla: yes

#335 fix: include proto d.ts in the build
  package.json
Labels: cla: yes

#336 Release @google-cloud/datastore v3.1.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#339 docs(samples): Update datastore_transaction_retry sample to use function arguments rather than closed variables.
  samples/concepts.js
Labels: cla: yes

#341 chore: update proto docs and code style
  protos/google/datastore/v1/datastore.proto
  protos/google/datastore/v1/entity.proto
  protos/google/datastore/v1/query.proto
  src/v1/doc/google/datastore/v1/doc_datastore.js
  src/v1/doc/google/datastore/v1/doc_entity.js
  src/v1/doc/google/datastore/v1/doc_query.js
  synth.metadata
Labels: cla: yes
