Repository googleapis/nodejs-datastore, pull requests merged in 2019-01, with the labels that each got.

#291 refactor: sprinkle some types about
  package.json
  src/entity.ts
  src/index.ts
  src/query.ts
  src/request.ts
  src/transaction.ts
  system-test/datastore.ts
  test/query.ts
  test/request.ts
Labels: cla: yes

#293 fix(docs): remove unused long running operations types
  src/v1/doc/google/protobuf/doc_wrappers.js
  synth.metadata
Labels: cla: yes

#294 fix(docs): fix namespace causing 404s
  src/index.ts
Labels: cla: yes

#298 Release @google-cloud/datastore v3.0.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#292 build: check broken links in generated docs
  .jsdoc.js
  .kokoro/docs.sh
  README.md
  package.json
Labels: cla: yes

#304 chore: update year in the license headers
  src/v1/datastore_client.js
  src/v1/doc/google/datastore/v1/doc_datastore.js
  src/v1/doc/google/datastore/v1/doc_entity.js
  src/v1/doc/google/datastore/v1/doc_query.js
  src/v1/doc/google/protobuf/doc_wrappers.js
  src/v1/index.js
  synth.metadata
  test/gapic-v1.js
Labels: cla: yes

#306 docs(key): copy Datastore#key examples to Key ctor
  src/entity.ts
Labels: cla: yes, type: docs

#310 fix(types): Make gaxOptions optional in Transaction.rollback()
  src/transaction.ts
Labels: cla: yes

#307 feat: typings for gapic files
  src/v1/datastore_client.d.ts
  src/v1/index.d.ts
Labels: cla: yes

#315 docs(samples): Update Datastore snippet for read only transaction
  samples/concepts.js
Labels: cla: yes
