Repository googleapis/nodejs-datastore, pull requests merged in 2019-03, with the labels that each got.

#347 [CHANGE ME] Re-generated to pick up changes in the API or client library generator.
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#346 fix: add missing package, and add install test
  package.json
  system-test/fixtures/sample/package.json
  system-test/fixtures/sample/src/index.ts
  system-test/fixtures/sample/tsconfig.json
  system-test/install.ts
Labels: cla: yes

#342 refactor(ts): enable noImplicitAny on test/query.ts
  test/query.ts
Labels: cla: yes

#343 refactor(ts): enable noImplicitAny on test/request.ts
  src/request.ts
  test/request.ts
Labels: cla: yes

#351 fix: include types in package
  package.json
Labels: cla: yes

#352 fix: make an explicit dependency on long
  package.json
  proto/datastore.d.ts
Labels: cla: yes

#353 Release @google-cloud/datastore v3.1.2
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes

#354 build(ci): use node10 for system-test and samples-test
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node10/lint.cfg
  .kokoro/continuous/node10/samples-test.cfg
  .kokoro/continuous/node10/system-test-grpcjs.cfg
  .kokoro/continuous/node10/system-test.cfg
  .kokoro/presubmit/node10/docs.cfg
  .kokoro/presubmit/node10/lint.cfg
  .kokoro/presubmit/node10/samples-test.cfg
  .kokoro/presubmit/node10/system-test-grpcjs.cfg
  .kokoro/presubmit/node10/system-test.cfg
Labels: cla: yes

#344 refactor(ts): enable noImplicitAny on test/transaction.ts
  src/request.ts
  src/transaction.ts
  test/transaction.ts
Labels: automerge, cla: yes

#356 fix(docs): move ts overloads above doc string
  src/index.ts
  src/query.ts
  src/request.ts
  src/transaction.ts
Labels: cla: yes

#359 build: Add docuploader credentials to node publish jobs
  .kokoro/release/publish.cfg
  synth.metadata
Labels: cla: yes

#355 refactor(ts): enable noImplicitAny in tsconfig
  test/request.ts
  tsconfig.json
Labels: cla: yes

#361 build: fix system tests
  system-test/datastore.ts
Labels: cla: yes, do not merge

#362 [CHANGE ME] Re-generated to pick up changes in the API or client library generator.
  src/v1/datastore_client.js
  synth.metadata
Labels: cla: yes

#364 build: use per-repo npm publish token
  .kokoro/release/publish.cfg
Labels: cla: yes

#367 chore: use wombat to publish to npm
  .kokoro/publish.sh
Labels: cla: yes

#372 fix: include 'x-goog-request-params' header in requests
  src/v1/datastore_client.js
  synth.metadata
Labels: cla: yes
