Repository googleapis/nodejs-datastore, pull requests merged in 2019-06, with the labels that each got.

#422 feat: support apiEndpoint override in client constructor
  src/v1/datastore_client.js
  synth.metadata
  test/gapic-v1.js
Labels: cla: yes

#424 fix: default options to empty object
  src/v1/datastore_client.js
  synth.metadata
  test/gapic-v1.js
Labels: cla: yes

#423 chore: release 4.1.0
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#425 refactor: changes formatting of various statements
  src/transaction.ts
  synth.metadata
Labels: cla: yes

#426 refactor: update formatting
  src/transaction.ts
  synth.metadata
Labels: cla: yes

#428 fix: added legacy samples back, until we can update external references
  README.md
  samples/README.md
  samples/tasks.js
  synth.metadata
  test/.eslintrc.yml
Labels: cla: yes

#431 fix(docs): link to up-to-date googleapis.dev doc site
  .repo-metadata.json
  README.md
  synth.metadata
Labels: cla: yes

#430 chore: release 4.1.1
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#432 docs: update return type in jsdoc for Buffers
  src/v1/datastore_client.js
  src/v1/doc/google/datastore/v1/doc_datastore.js
  src/v1/doc/google/datastore/v1/doc_entity.js
  src/v1/doc/google/datastore/v1/doc_query.js
  synth.metadata
Labels: cla: yes

#437 feat(docs): move to new googleapis.dev URL
  .repo-metadata.json
  README.md
Labels: cla: yes

#439 fix(docs): fix <caption> tag rendering in Key doc
  src/entity.ts
Labels: cla: yes

#436 fix: add `parseInt` to constructor of task keys
  samples/tasks.js
Labels: cla: yes

#435 fix: assign more restrictive type to PathType (#433)
  src/entity.ts
  src/index.ts
  system-test/datastore.ts
Labels: cla: yes

#440 build: switch to GitHub magic proxy, for release-please
  .kokoro/continuous/node10/test.cfg
  .kokoro/test.sh
  synth.metadata
Labels: cla: yes

#438 chore: release 4.1.2
  CHANGELOG.md
  package.json
  samples/package.json
Labels: :rotating_light:, autorelease: pending, cla: yes, type: process

#444 fix(docs): link to reference docs section on googleapis.dev
  .jsdoc.js
  README.md
Labels: cla: yes

#445 fix(typescript): query pojection -> projection
  src/v1/datastore_client.d.ts
Labels: cla: yes

#446 fix(typescript): import from 'grpc' -> '@grpc/grpc-js'
  src/v1/datastore_client.d.ts
Labels: cla: yes

#447 chore: release 4.1.3
  CHANGELOG.md
  package.json
  samples/package.json
Labels: autorelease: pending, cla: yes, type: process

#450 build: use config file for linkinator
  linkinator.config.json
  package.json
Labels: cla: yes
