Repository googleapis/nodejs-datastore, pull requests merged in 2020-06, with the labels that each got.

#673 build: update protos.js
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: automerge, cla: yes, context: none

#677 feat: move ts target to es2018 from es2016
  .kokoro/populate-secrets.sh
  .kokoro/publish.sh
  .kokoro/release/publish.cfg
  .kokoro/trampoline.sh
  protos/protos.js
  src/v1/datastore_client.ts
  synth.metadata
  tsconfig.json
Labels: automerge, cla: yes, context: partial

#682 fix: Insert arrays with NULL values
  src/entity.ts
  test/request.ts
Labels: cla: yes

#684 fix: proper fallback option handling
  protos/google/datastore/v1/datastore.proto
  protos/google/datastore/v1/entity.proto
  protos/google/datastore/v1/query.proto
  protos/protos.json
  src/v1/datastore_client.ts
  synth.metadata
Labels: cla: yes, context: partial

#688 chore(nodejs_templates): add script logging to node_library populate-secrets.sh
  .kokoro/populate-secrets.sh
  synth.metadata
Labels: cla: yes, context: full

#689 chore: update node issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  synth.metadata
Labels: automerge, cla: yes, context: full

#686 feat(synth): add datastore v1 admin api
  protos/google/datastore/admin/v1/datastore_admin.proto
  protos/google/datastore/admin/v1/index.proto
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  src/v1/datastore_admin_client.ts
  src/v1/datastore_admin_client_config.json
  src/v1/datastore_admin_proto_list.json
  src/v1/index.ts
  synth.metadata
  synth.py
  test/gapic_datastore_admin_v1.ts
Labels: cla: yes
