Repository googleapis/nodejs-datastore, pull requests merged in 2020-05, with the labels that each got.

#664 fix: regenerate files and fixed formatting, lint
  synth.metadata
  test/entity.ts
  test/gapic_datastore_v1.ts
Labels: automerge, cla: yes

#666 Create CODEOWNERS
  .github/CODEOWNERS
Labels: cla: yes

#665 docs: fix comments
  protos/google/datastore/v1/entity.proto
  synth.metadata
Labels: automerge, cla: yes

#667 build: do not fail builds on codecov errors (#528)
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#669 build: point to team in correct org
  .github/CODEOWNERS
Labels: cla: yes

#671 fix: missing await in rollback
  samples/concepts.js
  samples/tasks.js
  samples/tasks.markdone.js
  src/request.ts
  test/request.ts
Labels: cla: yes
