Repository googleapis/nodejs-datastore, pull requests merged in 2020-11, with the labels that each got.

#747 build(node): add KOKORO_BUILD_ARTIFACTS_SUBDIR to env
  .kokoro/trampoline_v2.sh
  synth.metadata
Labels: api: datastore, automerge, cla: yes, context: full

#748 docs: correct method name referenced by datastore.merge()
  src/request.ts
Labels: api: datastore, cla: yes, kokoro:force-run

#751 fix: do not modify options object, use defaultScopes
  package.json
  src/v1/datastore_admin_client.ts
  src/v1/datastore_client.ts
  synth.metadata
  synth.py
  system-test/fixtures/sample/src/index.ts
  system-test/install.ts
Labels: api: datastore, automerge, cla: yes

#749 Export Key and Entity.
  src/index.ts
Labels: api: datastore, cla: yes

#758 refactor: a couple of minor refactoring.
  src/entity.ts
Labels: api: datastore, cla: yes

#767 fix: storing an empty Buffer
  src/entity.ts
  system-test/datastore.ts
  test/entity.ts
Labels: api: datastore, cla: yes

#768 fix(browser): check for fetch on window
  README.md
  protos/protos.json
  src/v1/datastore_admin_client.ts
  src/v1/datastore_client.ts
  synth.metadata
Labels: api: datastore, automerge, cla: yes, context: partial
