Repository googleapis/nodejs-datastore, pull requests merged in 2020-10, with the labels that each got.

#735 chore: update bucket for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: cla: yes, context: full

#736 build(node_library): migrate to Trampoline V2
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node12/common.cfg
  .kokoro/docs.sh
  .kokoro/lint.sh
  .kokoro/populate-secrets.sh
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/publish.sh
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  .kokoro/release/docs.cfg
  .kokoro/release/docs.sh
  .kokoro/release/publish.cfg
  .kokoro/samples-test.sh
  .kokoro/system-test.sh
  .kokoro/test.sh
  .kokoro/trampoline.sh
  .kokoro/trampoline_v2.sh
  .trampolinerc
  synth.metadata
Labels: api: datastore, automerge: exact, cla: yes, context: full

#734 feat: introduce import/export + Index class
  package.json
  samples/export.js
  samples/import.js
  samples/indexes.get.js
  samples/indexes.list.js
  samples/test/import-export.test.js
  samples/test/indexes.test.js
  src/index-class.ts
  src/index.ts
  src/request.ts
  system-test/datastore.ts
  test/index-class.ts
  test/index.ts
  test/request.ts
Labels: api: datastore, cla: yes

#739 docs: updated README.md
  README.md
  samples/README.md
  synth.metadata
Labels: cla: yes, context: none

#740 build: only check --engine-strict for production deps
  .github/workflows/ci.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#741 chore: clean up Node.js TOC for cloud-rad
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#744 docs: updated code of conduct (includes update to actions)
  .github/workflows/ci.yaml
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: api: datastore, automerge, cla: yes, context: full
