Repository googleapis/nodejs-datastore, pull requests merged in 2020-07, with the labels that each got.

#695 build: use bazel build
  synth.metadata
  synth.py
Labels: automerge, cla: yes

#696 chore: update CODEOWNERS
  .github/CODEOWNERS
Labels: automerge, cla: yes

#700 build: typo from .gittatributes fix
  .gitattributes
  synth.metadata
Labels: cla: yes, context: none

#701 chore: delete Node 8 presubmit tests
  .kokoro/presubmit/node8/common.cfg
  .kokoro/presubmit/node8/test.cfg
Labels: automerge, cla: yes

#707 chore: add config files for cloud-rad for node.js
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs-devsite.sh
  api-extractor.json
  synth.metadata
Labels: automerge, cla: yes, context: full

#708 chore: add dev dependencies for cloud-rad ref docs
  package.json
Labels: automerge, cla: yes

#710 build: rename _toc to toc
  .kokoro/release/docs-devsite.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#711 chore: move gitattributes files to node templates
  .gitattributes
  synth.metadata
Labels: automerge, cla: yes, context: full

#712 chore(node): fix kokoro build path for cloud-rad
  .kokoro/release/docs-devsite.cfg
  synth.metadata
Labels: automerge, cla: yes, context: full

#713 build: update protos
  protos/protos.d.ts
  protos/protos.js
  synth.metadata
Labels: automerge, cla: yes, context: none

#714 docs: add links to the CHANGELOG from the README.md for Java and Node
  README.md
  synth.metadata
Labels: automerge, cla: yes, context: full
