Repository googleapis/nodejs-datastore, pull requests merged in 2020-09, with the labels that each got.

#693 fix: split insert, update, upsert
  src/index.ts
  src/request.ts
  src/transaction.ts
  test/index.ts
  test/request.ts
  test/transaction.ts
Labels: api: datastore, cla: yes

#728 build(test): recursively find test files; fail on unsupported dependency versions
  .github/workflows/ci.yaml
  .mocharc.js
  synth.metadata
Labels: automerge, cla: yes, context: full

#730 fix: await on commit operations in sample code
  samples/concepts.js
Labels: cla: yes

#731 docs: direct to documentation for datastore, not the product landing page
  .repo-metadata.json
  README.md
Labels: cla: yes

#733 docs: update documentation link for datastore
  samples/README.md
  synth.metadata
Labels: cla: yes, context: none

#732 test: fix flaky projection query test
  samples/concepts.js
  samples/test/concepts.test.js
Labels: api: datastore, cla: yes
