Repository googleapis/nodejs-datastore, pull requests merged in 2021-06, with the labels that each got.

#840 chore(nodejs): remove api-extractor dependencies
  package.json
Labels: api: datastore, automerge, cla: yes

#842 chore: create flakybot.yaml
  .github/flakybot.yaml
Labels: api: datastore, cla: yes

#848 fix: Resolve getProjectId
  src/index.ts
  system-test/datastore.ts
Labels: api: datastore, cla: yes

#849 fix(deps): google-gax v2.17.0 with mTLS
  package.json
Labels: api: datastore, automerge, cla: yes, owlbot:run
