Repository googleapis/nodejs-datastore, pull requests merged in 2021-05, with the labels that each got.

#808 docs: clarified key samples
  src/index.ts
Labels: api: datastore, cla: yes, samples

#824 build: update falsy types in protos.js
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: api: datastore, automerge, cla: yes, context: partial

#825 fix(deps): require google-gax v2.12.0
  package.json
Labels: api: datastore, automerge, cla: yes

#834 chore: migrate to owl bot
  .github/.OwlBot.lock.yaml
  .github/.OwlBot.yaml
  .github/generated-files-bot.yml
  .github/workflows/ci.yaml
  .kokoro/release/publish.cfg
  owlbot.py
  src/entity.ts
  src/request.ts
  src/v1/datastore_admin_client.ts
  src/v1/datastore_client.ts
  synth.metadata
  synth.py
  system-test/datastore.ts
  test/gapic_datastore_admin_v1.ts
  test/gapic_datastore_v1.ts
  test/index.ts
  test/query.ts
  test/request.ts
  test/transaction.ts
Labels: api: datastore, cla: yes
