Repository googleapis/nodejs-datastore, pull requests merged in 2021-02, with the labels that each got.

#789 chore: update CODEOWNERS config
  .repo-metadata.json
Labels: api: datastore, automerge, cla: yes

#790 build: adds UNORDERED_LIST enum
  protos/protos.d.ts
  protos/protos.js
  protos/protos.json
  synth.metadata
Labels: api: datastore, automerge, cla: yes, context: none

#792 chore: use repo metadata to populate nodejs CODEOWNERS
  .github/CODEOWNERS
  synth.metadata
Labels: api: datastore, automerge, cla: yes, context: full

#794 docs: fix database instance examples and description
  src/index.ts
Labels: api: datastore, automerge: exact, cla: yes
