Repository googleapis/nodejs-datastore, pull requests merged in 2024-10, with the labels that each got.

#1338 docs: Change description of DatastoreRequest class
  src/request.ts
Labels: api: datastore, size: xs

#1340 fix: query object description
  src/query.ts
Labels: automerge, api: datastore, size: xs

#1341 docs: Add descriptions to many parameters
  src/aggregate.ts
  src/entity.ts
  src/index.ts
  src/query.ts
  src/request.ts
  src/transaction.ts
Labels: automerge, api: datastore, size: s

#1342 docs: Add descriptions to more of the parameters
  src/entity.ts
  src/filter.ts
  src/index.ts
Labels: api: datastore, size: m

#1343 docs: Add parameters to second commit overload
  src/transaction.ts
Labels: api: datastore, size: xs

#1336 fix: The save function should not throw an error for name/value properties in arrays
  src/entity.ts
  system-test/datastore.ts
  test/entity/findLargeProperties_.ts
  test/gapic-mocks/commit.ts
Labels: api: datastore, size: l
